version: 2
updates:
- package-ecosystem: composer
  directory: "/site"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
