codecov:
  notify:
    require_ci_to_pass: true

ignore:
  - "tests/integrationTests"

coverage:
  status:
    project: false
    patch: false
    changes: false

comment:
  layout: "reach, diff, flags"
  behavior: once
