language: php
sudo: true
dist: trusty

cache:
  pip: true
  directories:
    - ${TRAVIS_BUILD_DIR}/site/vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2

  include:
    # Warm up the pip and composer caches to use it for the rest of the build stages
    - &00-cache
      stage: 00 warm up cache
      php: 7.0
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - pushd site
        - travis_retry composer install --prefer-dist --no-interaction
        - popd
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - pip3 install pause
        - pip3 install tzlocal
        - pip3 install paramiko
      script: skip
    - <<: *00-cache
      php: 7.1
      if: branch = master OR type = pull_request
    - <<: *00-cache
      php: 7.2
      if: branch = master OR type = pull_request

    # Lint the codebase to ensure that the code is compliant to our system
    - &01-lint
      stage: 01 lint
      php: 7.0
      script:
        - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - <<: *01-lint
      php: 7.1
      if: branch = master OR type = pull_request
    - <<: *01-lint
      php: 7.2
      if: branch = master OR type = pull_request

    - &02-php-unit
      stage: 02 unit test
      php: 7.0
      script:
        - pushd site
        - vendor/bin/phpunit --version
        - vendor/bin/phpunit --configuration tests/phpunit.xml
        - popd
      after_success:
        - pushd site
        - travis_retry php vendor/bin/coveralls -v
        - popd
    - <<: *02-php-unit
      php: 7.1
      if: branch = master OR type = pull_request
    - <<: *02-php-unit
      php: 7.2
      if: branch = master OR type = pull_request

    - &02-python-unit
      language: python
      python: 3.4
      install:
        - pip3 install -U pip
        - pip3 install tzlocal
      script:
        - pushd python_submitty_utils
        - python3 setup.py test
        - popd
    - <<: *02-python-unit
      python: 3.5
      if: branch = master OR type = pull_request
    - <<: *02-python-unit
      python: 3.6
      if: branch = master OR type = pull_request

    - &03-e2e
      stage: 03 e2e test
      php: 7.0
      env: AUTH_METHOD=1
      addons:
        chrome: stable
        postgresql: "9.5"
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          packages:
            - apache2
            - libapache2-mod-fastcgi
            - build-essential
            - automake
            - cmake
            - clang
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - google-chrome-stable
            - libpam-passwdqc
            - libboost-all-dev
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - PHP_VERSION=${TRAVIS_PHP_VERSION:0:3}
        - sudo add-apt-repository -y ppa:ondrej/php; sudo apt-get -qq update;
        - sudo apt-get -y install libapache2-mod-php${PHP_VERSION} php${PHP_VERSION}-pgsql php${PHP_VERSION}-curl; a2enmod php${PHP_VERSION};
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - pip3 install pause
        - pip3 install paramiko
        - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
      before_script:
        # Doing this helps chromedriver from hanging for some mysterious reason
        # https://github.com/SeleniumHQ/docker-selenium/issues/87
        - export DBUS_SESSION_BUS_ADDRESS=/dev/null
        - psql -U postgres -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
        - PGPASSWORD=submitty_dbuser psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
        - sudo bash .setup/travis/autograder.sh
        - bash .setup/travis/setup.sh
        - sudo python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/setup_sample_courses.py sample
        - sudo bash .setup/travis/setup_test_suite.sh
        - sudo sed -e "s?www-data?submitty_php?g" --in-place /etc/apache2/envvars
        - sudo a2enmod include rewrite actions cgi alias headers
        - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - sudo a2dissite 000-default
        - sudo rm -rf /etc/apache2/sites-available/*
        - sudo rm -rf /etc/apache2/sites-enabled/*
        - sudo cp -f .setup/travis/apache.conf /etc/apache2/sites-available/submitty.conf
        - sudo a2ensite submitty
        - sudo chown -R submitty_php:submitty_php /var/lib/apache2/fastcgi
        - sudo chmod -R 755 /usr/local/submitty
        - sudo chmod -R 777 /usr/local/submitty/test_suite
        - sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
        - sudo service apache2 restart
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      script:
        - TEST_URL="http://localhost" python -m unittest discover -v --start-directory tests
    - <<: *03-e2e
      php: 7.1
      if: branch = master OR type = pull_request
    - <<: *03-e2e
      php: 7.2
      if: branch = master OR type = pull_request
    - <<: *03-e2e
      php: 7.0
      env: AUTH_METHOD=2
    - <<: *03-e2e
      php: 7.1
      env: AUTH_METHOD=2
      if: branch = master OR type = pull_request
    - <<: *03-e2e
      php: 7.2
      env: AUTH_METHOD=2
      if: branch = master OR type = pull_request

    # To add additional test cases of Clang, you should choose a version that has a binary built and distributed for
    # it
    - &04-integration
      stage: Integration test
      language: cpp
      addons:
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          packages:
            - build-essential
            - automake
            - cmake
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - libboost-all-dev
      env: CLANG_VER="5.0.1"
      before_install:
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - sudo apt-get install clang
        - export LLVM_ARCHIVE_PATH=${HOME}/clang+llvm.tar.xz
        - wget http://releases.llvm.org/${CLANG_VER}/clang+llvm-${CLANG_VER}-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O ${LLVM_ARCHIVE_PATH}
        - mkdir ${HOME}/clang+llvm
        - tar xf ${LLVM_ARCHIVE_PATH} -C ${HOME}/clang+llvm --strip-components 1
        - export PATH=${HOME}/clang+llvm/bin:${PATH}
        - pip3 install -U pip
        - pip3 install PyYAML
        - pip3 install python-dateutil
        - pip3 install paramiko
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
        - sudo bash ./.setup/travis/autograder.sh
        - bash ./.setup/travis/setup.sh
        - sudo bash ./.setup/travis/setup_test_suite.sh
      script:
        - sudo python3 /usr/local/submitty/test_suite/integrationTests/run.py
    - <<: *04-integration
      env: CLANG_VER="6.0.0"
      if: branch = master OR type = pull_request

notifications:
  email: false
